### ISSUE TITLE
PostgreSQL 16 support

### ISSUE THREAD

**Issue by devrimgunduz** [fvannee/timestamp9#15]
Hi,

PostgreSQL 16 Beta 1 is out. 1.3.0 fails to compile against it. What are the plans for v16 support?

Regards, Devrim

```
[ 66%] Built target sqlfile
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c: In function 'parse_sane_timezone':
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:237:63: warning: passing argument 4 of 'DecodeTimezoneAbbrev' from incompatible pointer type [-Wincompatible-pointer-types]
  237 |                 type = DecodeTimezoneAbbrev(0, lowzone, &val, &tzp);
      |                                                               ^~~~
      |                                                               |
      |                                                               pg_tz **
In file included from /build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:15:
/usr/pgsql-16/include/server/utils/datetime.h:343:83: note: expected 'int *' but argument is of type 'pg_tz **'
  343 |                                                                  int *ftype, int *offset, pg_tz **tz,
      |                                                                              ~~~~~^~~~~~
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:237:24: error: too few arguments to function 'DecodeTimezoneAbbrev'
  237 |                 type = DecodeTimezoneAbbrev(0, lowzone, &val, &tzp);
      |                        ^~~~~~~~~~~~~~~~~~~~
/usr/pgsql-16/include/server/utils/datetime.h:342:17: note: declared here
  342 | extern int      DecodeTimezoneAbbrev(int field, const char *lowtoken,
      |                 ^~~~~~~~~~~~~~~~~~~~
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c: In function 'timestamp9_in':
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:311:17: error: too few arguments to function 'DecodeDateTime'
  311 |                 DecodeDateTime(field, ftype, nf, &dtype, p_tm, &fsec, &tz) != 0)
      |                 ^~~~~~~~~~~~~~
/usr/pgsql-16/include/server/utils/datetime.h:312:17: note: declared here
  312 | extern int      DecodeDateTime(char **field, int *ftype, int nf,
      |                 ^~~~~~~~~~~~~~
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:315:27: warning: declaration of 'ns' shadows a previous local [-Wshadow=compatible-local]
  315 |                 long long ns;
      |                           ^~
/build/pgrpms/rpm/redhat/main/non-common/timestamp9/main/timestamp9-timestamp9-1.3.0/src/timestamp9.c:287:19: note: shadowed declaration is here
  287 |         long long ns;
      |                   ^~
make[3]: *** [src/CMakeFiles/timestamp9.dir/build.make:76: src/CMakeFiles/timestamp9.dir/timestamp9.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:183: src/CMakeFiles/timestamp9.dir/all] Error 2
make[1]: *** [Makefile:156: all] Error 2

```

**Comment by fvannee** [comment]
Thanks for letting me know! I'll have a look and fix it.

-Floris

**Comment by fvannee** [comment]
It should work with just published timestamp9-1.4.0. Can you try?

**Comment by devrimgunduz** [comment]
Thanks, it works! Cheers, Devrim
